/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package labo6_renatovarela;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Asus Pc
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_crearMundo = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        tf_NombreMundo = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Lista_Mundos = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        Lista_Criaturas = new javax.swing.JList<>();
        jLabel14 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jd_listar = new javax.swing.JDialog();
        jButton12 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        Listar = new javax.swing.JTextArea();
        jd_AgregarCriatura = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_nombreCriatura = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        tf_Cantidad = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tf_MaximoAnos = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_region = new javax.swing.JTextField();
        tf_vida = new javax.swing.JTextField();
        Login = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_usuario = new javax.swing.JTextField();
        tf_contrasena = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Contrasena = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_key = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_Contrasena = new javax.swing.JPasswordField();
        Modificar = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        tf_Cantidad1 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tf_vida1 = new javax.swing.JTextField();
        tf_nombreCriatura1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tf_MaximoAnos1 = new javax.swing.JTextField();
        tf_region1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        JMI_Login = new javax.swing.JMenuItem();
        JMI_crear = new javax.swing.JMenuItem();
        JMI_listar = new javax.swing.JMenuItem();

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Nombre Del Mundo");

        jButton5.setText("Guardar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        Lista_Mundos.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(Lista_Mundos);

        Lista_Criaturas.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(Lista_Criaturas);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("Mundo");

        jButton7.setText("<------");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Boton de AGREGAR CRIATURA Para agregar una Criatura\nBoton de Guardar para guardar un mundo\n\nPara Agregar Criaturas al Mundo presiona boton de la\nflecha mientras tengas un mundo seleccionado\n");
        jScrollPane4.setViewportView(jTextArea1);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setText("Criatura");

        jButton8.setText("Modificar Criatura");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jButton9.setText("Agregar Criatura");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jButton11.setText("Eliminar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_crearMundoLayout = new javax.swing.GroupLayout(jd_crearMundo.getContentPane());
        jd_crearMundo.getContentPane().setLayout(jd_crearMundoLayout);
        jd_crearMundoLayout.setHorizontalGroup(
            jd_crearMundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearMundoLayout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(284, 284, 284))
            .addGroup(jd_crearMundoLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jd_crearMundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearMundoLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                        .addComponent(jButton7)
                        .addGap(134, 134, 134)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140))
                    .addGroup(jd_crearMundoLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(57, 57, 57)
                        .addComponent(tf_NombreMundo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton9)
                        .addGap(337, 337, 337))
                    .addGroup(jd_crearMundoLayout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton8)
                        .addGap(51, 51, 51)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161))))
            .addGroup(jd_crearMundoLayout.createSequentialGroup()
                .addGap(348, 348, 348)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_crearMundoLayout.setVerticalGroup(
            jd_crearMundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearMundoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jd_crearMundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(57, 57, 57)
                .addGroup(jd_crearMundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_crearMundoLayout.createSequentialGroup()
                        .addGroup(jd_crearMundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tf_NombreMundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jd_crearMundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_crearMundoLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_crearMundoLayout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(jButton7))))
                    .addGroup(jd_crearMundoLayout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(jd_crearMundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton8)
                    .addComponent(jButton11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jButton12.setText("Buscar Un mundo para Listar");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });

        Listar.setColumns(20);
        Listar.setRows(5);
        jScrollPane5.setViewportView(Listar);

        javax.swing.GroupLayout jd_listarLayout = new javax.swing.GroupLayout(jd_listar.getContentPane());
        jd_listar.getContentPane().setLayout(jd_listarLayout);
        jd_listarLayout.setHorizontalGroup(
            jd_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listarLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jd_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jd_listarLayout.setVerticalGroup(
            jd_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listarLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jButton12)
                .addGap(48, 48, 48)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Nombre de la Criatura");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Criaturas");

        jButton1.setText("Guardar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Cantidad de Energia");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Numero Maximo de Años");

        tf_MaximoAnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_MaximoAnosActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Nombre de la Region");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Cantidad vivas de esa Especie");

        tf_region.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_regionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_AgregarCriaturaLayout = new javax.swing.GroupLayout(jd_AgregarCriatura.getContentPane());
        jd_AgregarCriatura.getContentPane().setLayout(jd_AgregarCriaturaLayout);
        jd_AgregarCriaturaLayout.setHorizontalGroup(
            jd_AgregarCriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AgregarCriaturaLayout.createSequentialGroup()
                .addGroup(jd_AgregarCriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_AgregarCriaturaLayout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jLabel2))
                    .addGroup(jd_AgregarCriaturaLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(jd_AgregarCriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(32, 32, 32)
                        .addGroup(jd_AgregarCriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tf_nombreCriatura, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_Cantidad, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_MaximoAnos, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_region, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_vida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_AgregarCriaturaLayout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jd_AgregarCriaturaLayout.setVerticalGroup(
            jd_AgregarCriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AgregarCriaturaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jd_AgregarCriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_nombreCriatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jd_AgregarCriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jd_AgregarCriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(tf_MaximoAnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jd_AgregarCriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_region, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jd_AgregarCriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tf_vida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Usuario");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Contrasena");

        tf_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_usuarioActionPerformed(evt);
            }
        });

        jButton2.setText("Crear Contrasena");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Ingresar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Login");

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login.getContentPane());
        Login.getContentPane().setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LoginLayout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(73, 73, 73)
                                .addComponent(jButton3))
                            .addGroup(LoginLayout.createSequentialGroup()
                                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(72, 72, 72)
                                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_contrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                    .addComponent(tf_usuario)))))
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(jLabel5)))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel5)
                .addGap(67, 67, 67)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(174, Short.MAX_VALUE))
        );

        jLabel6.setText("Key");

        jLabel7.setText("Contrasena");

        jButton4.setText("Crear");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton4KeyPressed(evt);
            }
        });

        jLabel8.setText("Crear Contrasena");

        javax.swing.GroupLayout ContrasenaLayout = new javax.swing.GroupLayout(Contrasena.getContentPane());
        Contrasena.getContentPane().setLayout(ContrasenaLayout);
        ContrasenaLayout.setHorizontalGroup(
            ContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContrasenaLayout.createSequentialGroup()
                .addGroup(ContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContrasenaLayout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addGroup(ContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jButton4)))
                    .addGroup(ContrasenaLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(ContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(70, 70, 70)
                        .addGroup(ContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Contrasena)
                            .addComponent(txt_key, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        ContrasenaLayout.setVerticalGroup(
            ContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContrasenaLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel8)
                .addGap(42, 42, 42)
                .addGroup(ContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_key, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(ContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_Contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(jButton4)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Cantidad de Energia");

        jButton10.setText("Guardar");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Numero Maximo de Años");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Nombre de la Criatura");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setText("Criaturas");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Nombre de la Region");

        tf_MaximoAnos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_MaximoAnos1ActionPerformed(evt);
            }
        });

        tf_region1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_region1ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Cantidad vivas de esa Especie");

        javax.swing.GroupLayout ModificarLayout = new javax.swing.GroupLayout(Modificar.getContentPane());
        Modificar.getContentPane().setLayout(ModificarLayout);
        ModificarLayout.setHorizontalGroup(
            ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarLayout.createSequentialGroup()
                .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModificarLayout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jLabel19))
                    .addGroup(ModificarLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(32, 32, 32)
                        .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tf_nombreCriatura1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_Cantidad1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_MaximoAnos1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_region1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_vida1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ModificarLayout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        ModificarLayout.setVerticalGroup(
            ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tf_nombreCriatura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tf_Cantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(tf_MaximoAnos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tf_region1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tf_vida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton6.setText("Salir");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jMenu1.setText("Archivo");

        JMI_Login.setText("Login");
        JMI_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_LoginActionPerformed(evt);
            }
        });
        jMenu1.add(JMI_Login);

        JMI_crear.setText("Crear");
        JMI_crear.setEnabled(false);
        JMI_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_crearActionPerformed(evt);
            }
        });
        jMenu1.add(JMI_crear);

        JMI_listar.setText("Listar");
        JMI_listar.setEnabled(false);
        JMI_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_listarActionPerformed(evt);
            }
        });
        jMenu1.add(JMI_listar);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(312, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(341, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMI_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_crearActionPerformed
        jd_crearMundo.setModal(true);
        jd_crearMundo.pack();
        jd_crearMundo.setLocationRelativeTo(this);
        jd_crearMundo.setVisible(true);
    }//GEN-LAST:event_JMI_crearActionPerformed

    private void JMI_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_listarActionPerformed
        jd_listar.setModal(true);
        jd_listar.pack();
        jd_listar.setLocationRelativeTo(this);
        jd_listar.setVisible(true);
    }//GEN-LAST:event_JMI_listarActionPerformed

    private void JMI_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_LoginActionPerformed
        
                Login.setModal(true);
        Login.pack();
        Login.setLocationRelativeTo(this);
        Login.setVisible(true);
    }//GEN-LAST:event_JMI_LoginActionPerformed

    private void tf_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_usuarioActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        Contrasena.setModal(true);
        Contrasena.pack();
        Contrasena.setLocationRelativeTo(this);
        Contrasena.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyPressed
             
    }//GEN-LAST:event_jButton4KeyPressed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
          String contrasena = txt_Contrasena.getText(),cifrar ="";
       int key = Integer.parseInt(txt_key.getText());
       int num;
       char cesar;
        for (int i = 0; i < contrasena.length(); i++) {
            num = contrasena.codePointAt(i);
           
            if (num == 122) {
                num = 65;
            }
            
            if (num == 90) {
                num = 97;
            }
            
            cesar = (char)(num+key);
            cifrar+=cesar;
        }
        
        try {
            escribirArchivo(key , cifrar);
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        txt_Contrasena.setText("");
        txt_key.setText("");
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
       
        String contrasena = "";
        String usuario = "";
        int key = 0;
        Scanner sc = null;
        File archivo;

        try {

            archivo = new File("./Credenciales.txt");
            sc = new Scanner(archivo);
            sc.useDelimiter(";");

                usuario = sc.next();
                contrasena = sc.next();
                key = sc.nextInt();
 
      
            

        } catch (Exception e) {
            e.printStackTrace();
        }
        
       contrasena = desifrar(contrasena , key);
        
        if (tf_usuario.getText().equals(usuario) && tf_contrasena.getText().equals(contrasena)) {
            JMI_Login.setEnabled(false);
           
            JMI_Login.setEnabled(true);
          
            JMI_crear.setEnabled(true);
            JMI_listar.setEnabled(true);
            Login.setVisible(false);
        }

        sc.close();


       
    }//GEN-LAST:event_jButton3MouseClicked

    private void tf_MaximoAnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_MaximoAnosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_MaximoAnosActionPerformed

    private void tf_regionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_regionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_regionActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       try{
        String nombre;
        int cantidad_vital;
        int maximo_anos;
        String nombre_region;
        int cantidad_vida;

        nombre = tf_nombreCriatura.getText();
        cantidad_vital = Integer.parseInt(tf_Cantidad.getText());
        maximo_anos = Integer.parseInt(tf_MaximoAnos.getText());
        nombre_region = tf_region.getText();
        cantidad_vida = Integer.parseInt(tf_vida.getText());

        DefaultListModel modeloLISTA = (DefaultListModel) Lista_Criaturas.getModel();

        Criaturas criatura = new Criaturas(nombre, cantidad_vital, maximo_anos, nombre_region, cantidad_vida);
        criaturas.add(criatura);

        modeloLISTA.addElement(criatura);
        Lista_Criaturas.setModel(modeloLISTA);

        tf_nombreCriatura.setText("");
        tf_Cantidad.setText("");
        tf_MaximoAnos.setText("");
        tf_vida.setText("");
        tf_region.setText("");
       }catch(Exception e){
           JOptionPane.showMessageDialog(this, "Revise si ingreso los datos correctos");
       }

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        
        Archivo obtener = new Archivo();
        
        String direccion;
        
       
        
           for (int i = 0; i < listaMundo.size(); i++) {
            System.out.println(listaMundo.get(i));
            for (int j = 0; j < listaMundo.get(i).getCriaturas().size(); j++) {
                 System.out.println(listaMundo.get(i).getCriaturas()+"****");
            }
        }
        
        
        
        try{
            
            
            
            for (int i = 0; i < listaMundo.size(); i++) {
                
               
                String nombre = listaMundo.get(i).getNombre();
                direccion = "./Mundos/"+nombre+".txt";
                
                escribirarchivo(direccion,listaMundo.get(i));
                //obtener.cargararchivo();
                           
                        
            }
            
            
        }catch(IOException ex){
            //JOptionPane(this,"Verifique que hizo mal");
        }
         
        
        
        this.dispose();
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        String nombre;
        int cantidad_vital;
        int maximo_anos;
        String nombre_region;
        int cantidad_vida;

        nombre = tf_NombreMundo.getText();
        

        DefaultListModel modeloLISTA = (DefaultListModel) Lista_Mundos.getModel();

        MundoDisco mundo = new MundoDisco(nombre);
        
        listaMundo.add(mundo);
        
        
        

        modeloLISTA.addElement(mundo);
        Lista_Mundos.setModel(modeloLISTA);

        tf_NombreMundo.setText("");


    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
        
        jd_AgregarCriatura.setModal(true);
        jd_AgregarCriatura.pack();
        jd_AgregarCriatura.setLocationRelativeTo(this);
        jd_AgregarCriatura.setVisible(true);
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
      
        DefaultListModel modeloLISTA = (DefaultListModel) Lista_Mundos.getModel();
        DefaultListModel modeloLISTA2 = (DefaultListModel) Lista_Criaturas.getModel();
        
        MundoDisco m = (MundoDisco)modeloLISTA.getElementAt(Lista_Mundos.getSelectedIndex());
        m.getCriaturas().add((Criaturas)modeloLISTA2.getElementAt(Lista_Criaturas.getSelectedIndex()));
        
        modeloLISTA2.remove(Lista_Criaturas.getSelectedIndex());
        
     
        
        
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
         DefaultListModel modeloLISTA2 = (DefaultListModel) Lista_Criaturas.getModel();
       
       Criaturas criatura = (Criaturas)modeloLISTA2.getElementAt(Lista_Criaturas.getSelectedIndex());
       try{ 
       
       String nombre;
    int cantidad_vital;
    int maximo_anos;
    String nombre_region;
    int cantidad_vida;
        
         nombre = tf_nombreCriatura1.getText();
    cantidad_vital = Integer.parseInt(tf_Cantidad1.getText());
    maximo_anos = Integer.parseInt(tf_MaximoAnos1.getText());
    nombre_region = tf_region1.getText();
    cantidad_vida = Integer.parseInt( tf_vida1.getText());
    
    criatura.setNombre(nombre);
    criatura.setCantidad_vida(cantidad_vida);
    criatura.setMaximo_anos(maximo_anos);
    criatura.setNombre_region(nombre_region);
    criatura.setCantidad_vital(cantidad_vital);
    
       }catch(Exception e){
           JOptionPane.showInputDialog("Revise los errors");
       }
    
       tf_nombreCriatura1.setText("");
        tf_Cantidad1.setText("");
        tf_MaximoAnos1.setText("");
        tf_vida1.setText("");
        tf_region1.setText("");
        
    
    }//GEN-LAST:event_jButton10MouseClicked

    private void tf_MaximoAnos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_MaximoAnos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_MaximoAnos1ActionPerformed

    private void tf_region1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_region1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_region1ActionPerformed

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
       DefaultListModel modeloLISTA2 = (DefaultListModel) Lista_Criaturas.getModel();
       
       Criaturas criatura = (Criaturas)modeloLISTA2.getElementAt(Lista_Criaturas.getSelectedIndex());
       
       
       
         String nombre;
    int cantidad_vital;
    int maximo_anos;
    String nombre_region;
    int cantidad_vida;
    
    tf_nombreCriatura1.setText(criatura.getNombre());
    tf_MaximoAnos1.setText(Integer.toString(criatura.getMaximo_anos()));
    tf_vida1.setText(Integer.toString(criatura.getCantidad_vida()));
    tf_region1.setText(criatura.getNombre_region());
    tf_Cantidad1.setText(Integer.toString(criatura.getCantidad_vital()));
    
    
        Modificar.setModal(true);
        Modificar.pack();
        Modificar.setLocationRelativeTo(this);
        Modificar.setVisible(true);
    
   
    
       
        

        
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
      DefaultListModel modeloLISTA2 = (DefaultListModel) Lista_Criaturas.getModel();
       
       Criaturas criatura = (Criaturas)modeloLISTA2.getElementAt(Lista_Criaturas.getSelectedIndex());
       
       modeloLISTA2.remove(Lista_Criaturas.getSelectedIndex());
       
       
       
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
            
        File fichero = null;
        FileReader fr = null;
        BufferedReader br = null;
        
        
        
        Listar.setText("");
        
        try{
            JFileChooser jfc = new JFileChooser("./Mundos");
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de Texto","txt");
            
            FileNameExtensionFilter filtro2 = new FileNameExtensionFilter("Imagenes","jpg","png","bmp");
            
            jfc.setFileFilter(filtro);
            
            jfc.addChoosableFileFilter(filtro2);
            
            int seleccion = jfc.showOpenDialog(this);
            if (seleccion == JFileChooser.APPROVE_OPTION) {
                fichero = jfc.getSelectedFile();
                fr = new FileReader(fichero);
                br = new BufferedReader(fr);
                String linea;
                 Listar.setText("");
                
                while ((linea=br.readLine()) != null) {
                     Listar.append(linea);
                     Listar.append("\n");
                    
                }
            }
            
        }catch(Exception e){
            e.printStackTrace();
        }
        
        try{
            br.close();
            fr.close();
        }catch(IOException ex){
            
        }  
    }//GEN-LAST:event_jButton12MouseClicked
      public String desifrar(String contra , int key){
      String cifrar ="";
       //int key = Integer.parseInt(txt_key.getText());
       int num;
       char cesar;
        for (int i = 0; i < contra.length(); i++) {
            num = contra.codePointAt(i);
           
            if (num == 122) {
                num = 65;
            }
            
            if (num == 90) {
                num = 97;
            }
            
            cesar = (char)(num-key);
            cifrar+=cesar;
        }
        
     
          
          return cifrar;
      }
    
    
      public void escribirArchivo(int key , String contra) throws IOException{
           FileWriter fw = null;
        BufferedWriter bw = null;
        try{
        fw = new FileWriter("./Credenciales.txt",false);
        bw = new BufferedWriter(fw);
       
            bw.write("xXxGranATuinxXx;");
            bw.write(contra+";");
            bw.write(key+";");
      
        
        bw.flush();
        }
        catch(Exception e){
            //System.out.println("hasbdkasdbjas");
        }
        bw.close();
        fw.close();
       
        
    }
      
   public void escribirarchivo(String direccion, MundoDisco m) throws IOException{
          System.out.println("-******************");
          
          /*for (int i = 0; i < listaMundo.size(); i++) {
              for (int j = 0; j < listaMundo.get(i).getCriaturas().size(); j++) {
                  System.out.println(listaMundo.get(i).getCriaturas().get(i));
              }
              
          }*/
          
          
        FileWriter fw = null;
        BufferedWriter bw = null;
        try{
        fw = new FileWriter(direccion,false);
        bw = new BufferedWriter(fw);
         bw.write("Nombre: " + m.getNombre()+";");
              bw.newLine();
             
                for (int i = 0; i < m.getCriaturas().size(); i++) {
                    bw.write("------------------------------------------------------------------------------------");
                    bw.newLine();
                    bw.write("Nombre Criatura: " + m.getCriaturas().get(i).getNombre() + ",");
                    bw.newLine();
                    bw.write("Cantidad de vida: " + m.getCriaturas().get(i).getCantidad_vida() + ",");
                    bw.newLine();
                    bw.write("Cantidad Vital: " + m.getCriaturas().get(i).getCantidad_vital() + ",");
                    bw.newLine();
                    bw.write("Nombre de la Region: " + m.getCriaturas().get(i).getNombre_region() + ",");
                    bw.newLine();
                    bw.write("Cantidad Maxima de Años: " + m.getCriaturas().get(i).getMaximo_anos() + "");
                    bw.write(";");
                     bw.newLine();


            }
        bw.flush();
        }
        catch(Exception e){
            
        }
        bw.close();
        fw.close();
    }
    
    
    
    public void cargararchivo(){
        
      /* Scanner sc = null;
        m = new ArrayList();
        if (archivo.exists()) {
            try {
                sc = new Scanner(archivo);
                sc.useDelimiter(";");
                while (sc.hasNext()) {
                    m.add(new MundoDisco(sc.next()));
                    
                    ArrayList<Criaturas> temp = m.get(m.size() - 1).getCriaturas();
                    Scanner sc2 = new Scanner(sc.next());
                    sc2.useDelimiter(",");
                    
                    while (sc2.hasNext()) {                        
                        temp.add(new Criaturas(sc.next(), sc.nextInt(), sc.nextInt(), sc.next(), sc.nextInt()));
                    }
                    
                    m.get(m.size() - 1).setCriaturas(temp);
                    
                }
            }
        catch(Exception e){
            
        }
        sc.close();
        }
        
        
        
        
        */
        
    }
      
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Contrasena;
    private javax.swing.JMenuItem JMI_Login;
    private javax.swing.JMenuItem JMI_crear;
    private javax.swing.JMenuItem JMI_listar;
    private javax.swing.JList<String> Lista_Criaturas;
    private javax.swing.JList<String> Lista_Mundos;
    private javax.swing.JTextArea Listar;
    private javax.swing.JDialog Login;
    private javax.swing.JDialog Modificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JDialog jd_AgregarCriatura;
    private javax.swing.JDialog jd_crearMundo;
    private javax.swing.JDialog jd_listar;
    private javax.swing.JTextField tf_Cantidad;
    private javax.swing.JTextField tf_Cantidad1;
    private javax.swing.JTextField tf_MaximoAnos;
    private javax.swing.JTextField tf_MaximoAnos1;
    private javax.swing.JTextField tf_NombreMundo;
    private javax.swing.JTextField tf_contrasena;
    private javax.swing.JTextField tf_nombreCriatura;
    private javax.swing.JTextField tf_nombreCriatura1;
    private javax.swing.JTextField tf_region;
    private javax.swing.JTextField tf_region1;
    private javax.swing.JTextField tf_usuario;
    private javax.swing.JTextField tf_vida;
    private javax.swing.JTextField tf_vida1;
    private javax.swing.JPasswordField txt_Contrasena;
    private javax.swing.JTextField txt_key;
    // End of variables declaration//GEN-END:variables
     ArrayList<Criaturas> criaturas = new ArrayList();
     
    MundoDisco mundo = new MundoDisco();
    ArrayList<MundoDisco> listaMundo = new ArrayList();

}
